version: "3.2"
services:
  airsonic:
    image: linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=NewZealand/Auckland
    volumes:
      - /mnt/docker/airsonic/config:/config
      - /mnt/nasMedia/Music/Lidarr:/music
      - /mnt/nasMedia/Music/playlists:/playlists
      - /mnt/nasMedia/Music/podcasts:/podcasts
    ports:
      - 4040:4040
    restart: unless-stopped
